// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUwUAohmuwanb5UdC6yLjGqoDDsDExPBk',
    appId: '1:565292427051:web:dd4b9f3af861b8645bc76e',
    messagingSenderId: '565292427051',
    projectId: 'tea-minds',
    authDomain: 'tea-minds.firebaseapp.com',
    storageBucket: 'tea-minds.firebasestorage.app',
    measurementId: 'G-E0HJHBEB4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-kSkPTEacPGHMQft_t9nVE6q0V-kloZI',
    appId: '1:565292427051:android:616eff01f592de705bc76e',
    messagingSenderId: '565292427051',
    projectId: 'tea-minds',
    storageBucket: 'tea-minds.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdyHNk3VyV4QfF76BQ4AjlTgU3ZaO1K2Q',
    appId: '1:565292427051:ios:8403cf6ea346ed025bc76e',
    messagingSenderId: '565292427051',
    projectId: 'tea-minds',
    storageBucket: 'tea-minds.firebasestorage.app',
    iosBundleId: 'com.example.teaMinds',
  );
}
